name: "18789"

on:
  # schedule:
  #   - cron: "0 * * * *"
  push:
    branches: [main]

jobs:
  job:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-gcc@v1
      - run: tree
      - run: gcc ./18789/main.c -o ./18789/main.exe
      - run: ./18789/main.exe 100
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ./18789/save/
