name: '18789'

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  job:
    name: Run Script
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: git pull origin main
      - run: ./main.exe 5000
        working-directory: './18789'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ./save/*
