name: '18789'

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ main ]

jobs:
  job:
    name: Run Script
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./18789/main.exe 5000
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v10.1
        id: verify-changed-files
        with:
          files: |
             ./18789/save/*
      - name: Commit & Push If File Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: git add ./18789/save/* && git push origin main
