name: '18789'

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ main ]

jobs:
  job:
    name: Run Script
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./18789/main.exe 5000
      - run: git add ./18789/save && git commit -m "test!" && git push origin main
