name: '18789'

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  job:
    name: Run Script
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: git pull origin main
      - name: Run
        run: ./main.exe 5000
        working-directory: './18789'
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - name: hi
        run: git add ./save
        working-directory: './18789'
      - run: git commit -m "Apply automatic changes"
      - run: git push origin main
